version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sagemaker-auto-shutdown"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18ddmz3twemo5"
s3_prefix = "sagemaker-auto-shutdown"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
